-- CREATE SCHEMA

CREATE SCHEMA IF NOT EXISTS api;

-- DROP TABLES

DROP TABLE IF EXISTS api.users;
DROP TABLE IF EXISTS api.cars;

-- CREATE TABLES

CREATE TABLE IF NOT EXISTS api.users();
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS id             SERIAL PRIMARY KEY;
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS username       VARCHAR(200) NOT NULL;
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS email          VARCHAR(200) UNIQUE NOT NULL;
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS "address"      VARCHAR(200) NOT NULL;
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS password_hash  BYTEA NOT NULL;
ALTER TABLE api.users ADD COLUMN IF NOT EXISTS created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TABLE IF NOT EXISTS api.cars();
ALTER TABLE api.cars ADD COLUMN IF NOT EXISTS id             SERIAL PRIMARY KEY;
ALTER TABLE api.cars ADD COLUMN IF NOT EXISTS user_id        INTEGER NOT NULL;
ALTER TABLE api.cars ADD COLUMN IF NOT EXISTS color          VARCHAR(200) NOT NULL;
ALTER TABLE api.cars ADD COLUMN IF NOT EXISTS created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE api.cars ADD CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES api.users(id);